export { BasicInfoSection } from './BasicInfoSection'
export { InterestSection } from './InterestSection'
export { PaymentSection } from './PaymentSection'
export { PenaltySection } from './PenaltySection'
export { RecurrenceSection } from './RecurrenceSection'
export { TotalSection } from './TotalSection'
